### ISSUE TITLE
Java 8 dependency

### ISSUE THREAD

**Issue by planetguy32** [elifoster/Ping#5]
In Config's static constructor, there's a reference to String.join(CharStream, CharStream), which is only introduced in Java 8.

**Comment by elifoster** [comment]
Are you sure it isn't introduced until then? Gradle should have yelled at me about that, like it did when I used a switch statement on a String.

**Comment by planetguy32** [comment]
A friend sent [this log](http://paste.ubuntu.com/13429300/) to me. Oracle says the [relevant method](http://docs.oracle.com/javase/8/docs/api/java/lang/String.html#join-java.lang.CharSequence-java.lang.CharSequence...-) is new in Java 1.8.

**Comment by elifoster** [comment]
Oh, huh. I'll see if I can change the dependency listing on CurseForge. I'm not going to change anything in the code; you should just have your friend install Java 8 because it should work on their computer, and more and more mods are going to be having it as a hard dependency.

In March of 2015, over 60% of Minecraft users were using Java8, and this number has only gone up since then.

If you disagree with my decision to not change any code to allow for Java 7 users, please let me know your opinions as I'd love to hear them.

**Comment by planetguy32** [comment]
I don't have a problem with requiring Java 8, but if you do I'd appreciate it if the bytecode had its minimum Java version set accordingly - then it'll fail with a slightly less opaque UnsupportedClassVersionError. My friend probably should be using Java 8 anyway.

**Comment by elifoster** [comment]
Alright. I'll update the gradle and release a new version hard depping J8 soon.
